# Generated by Django 5.2.11 on 2026-02-24 21:31

from django.utils import timezone
from django.db import migrations, models


def preserve_date_deadlines_as_end_of_day(apps, schema_editor):
    Goal = apps.get_model('goals', 'Goal')
    current_tz = timezone.get_current_timezone()
    goals_to_update = []

    for goal in Goal.objects.exclude(deadline__isnull=True).iterator():
        deadline = goal.deadline
        if timezone.is_naive(deadline):
            deadline = timezone.make_aware(deadline, current_tz)
        else:
            deadline = timezone.localtime(deadline, current_tz)

        if (
            deadline.hour == 0
            and deadline.minute == 0
            and deadline.second == 0
            and deadline.microsecond == 0
        ):
            goal.deadline = deadline.replace(hour=23, minute=59, second=59, microsecond=0)
            goals_to_update.append(goal)

    if goals_to_update:
        Goal.objects.bulk_update(goals_to_update, ['deadline'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_date_deadlines_as_end_of_day, noop_reverse),
    ]
